"""add_tsvector_and_isolated_gin_index

Revision ID: 0adff2337a00
Revises: aee7fbcee69a
Create Date: 2026-05-26 22:42:13.582916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0adff2337a00'
down_revision: Union[str, Sequence[str], None] = 'aee7fbcee69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_resumes', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_resumes_search_vector', 'tenant_resumes', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resumes_search_vector', table_name='tenant_resumes', postgresql_using='gin')
    op.drop_column('tenant_resumes', 'search_vector')
    # ### end Alembic commands ###
